name: Ejecutar Script de Shell

on:
  push:
    branches:
      - main

jobs:
  build-app:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
    - name: Checkout of source code
      uses: actions/checkout@v2

    - name: Check versions
      run: bash pre-init.sh
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
     - name: Access Azure Key Vault
        run: |
          keyvault_url=${{ secrets.AZURE_KEYVAULT_URL }}
          client_id=${{ secrets.AZURE_CLIENT_ID }}
          client_secret=${{ secrets.AZURE_CLIENT_SECRET }}
          tenant_id=${{ secrets.AZURE_TENANT_ID }}

          # Your commands to interact with Azure Key Vault using Azure CLI or other tools.
        env:
          KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
        # auth-type: IDENTITY          
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     enable-AzPSSession: "true"

    # - name: Listar Recursos de Azure
    #   run: az group list --allow-no-subscriptions
      
    - name: config
      run: bash config.sh

    - name: Clean
      run: bash pre-build.sh

    - name: Build and push
      run: bash docker-build-push.sh

    #- name: destroy
    # run: destroy.sh
