name: Ejecutar Script de Shell

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout of source code
      uses: actions/checkout@v2
    
    - name: Check versions
      run: bash pre-init.sh

    - name: config
      run: bash config.sh

    - name: Clean
      run: bash pre-build.sh

    - name: Build and push
      run: bash docker-build-push.sh

    #- name: destroy
    # run: destroy.sh
